/**
 * options.js — Slumber options page controller
 *
 * Sections: General | Whitelist | License | Stats
 *
 * All communication with the background worker goes through
 * chrome.runtime.sendMessage — same message API as the popup.
 * Stats are read directly from storage.local (no worker message needed).
 *
 * License section uses Paddle Billing. Pro status is written to
 * chrome.storage.sync so it syncs with the user's Chrome account.
 */

// ---------------------------------------------------------------------------
// Config — update both values before release
// PADDLE_PAYMENT_LINK : Paddle dashboard → Checkout → Payment Links
// VALIDATE_ENDPOINT   : your deployed Cloudflare Worker URL
// ---------------------------------------------------------------------------

const PADDLE_PAYMENT_LINK = 'https://dkhan.dev/checkout?product=slumber-pro';
const VALIDATE_ENDPOINT   = 'https://dkhandev-site-payment-worker.wolf001349.workers.dev/validate';

// Matches keys generated by the Cloudflare Worker: XXXX-XXXX-XXXX-XXXX
const LICENSE_KEY_RE = /^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/i;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const $ = id => document.getElementById(id);

function msg(type, payload = {}) {
  return chrome.runtime.sendMessage({ type, payload });
}

function showSaveConfirm(id) {
  const el = $(id);
  if (!el) return;
  el.hidden = false;
  clearTimeout(el._timer);
  el._timer = setTimeout(() => { el.hidden = true; }, 2200);
}

// ---------------------------------------------------------------------------
// Navigation
// ---------------------------------------------------------------------------

const navItems  = document.querySelectorAll('.nav-item');
const sections  = document.querySelectorAll('.section');

function activateSection(name) {
  navItems.forEach(a => a.classList.toggle('active', a.dataset.section === name));
  sections.forEach(s => {
    const match = s.id === `section-${name}`;
    s.hidden = !match;
    if (!match) s.classList.remove('active');
    else s.classList.add('active');
  });

  // Lazy-load section data on first visit
  if (name === 'stats')     loadStats();
  if (name === 'license')   loadLicense();
  if (name === 'whitelist') loadWhitelist();
  if (name === 'schedule')  loadSchedule();
  if (name === 'shortcuts') loadShortcuts();
}

navItems.forEach(a => {
  a.addEventListener('click', e => {
    e.preventDefault();
    activateSection(a.dataset.section);
  });
});

// Handle direct hash navigation (e.g. chrome opens options to #license)
function routeFromHash() {
  const hash = location.hash.slice(1);
  const valid = ['general', 'shortcuts', 'schedule', 'whitelist', 'license', 'stats'];
  activateSection(valid.includes(hash) ? hash : 'general');
}
window.addEventListener('hashchange', routeFromHash);

// ---------------------------------------------------------------------------
// Config — update before submission
// ---------------------------------------------------------------------------

const GITHUB_URL = 'https://github.com/DKhanDev/Slumber';

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

async function init() {
  const manifest = chrome.runtime.getManifest();
  const verEl = $('version-label');
  if (verEl) verEl.textContent = `v${manifest.version}`;

  // Wire GitHub sidebar link
  const ghLink = $('link-github');
  if (ghLink) ghLink.href = GITHUB_URL;

  const [settingsRes, { slumber_license }] = await Promise.all([
    msg('GET_SETTINGS'),
    chrome.storage.sync.get('slumber_license'),
  ]);
  if (settingsRes.ok) {
    applySettings(settingsRes.settings, Boolean(slumber_license?.valid));
    _whitelist = settingsRes.settings.whitelist ?? [];
  }

  bindGeneralEvents();
  bindShortcutsEvents();
  bindScheduleEvents();
  bindWhitelistEvents();
  bindLicenseEvents();
  bindStatsEvents();
  await maybeShowWelcomeCard();

  routeFromHash();
}

// ---------------------------------------------------------------------------
// General settings
// ---------------------------------------------------------------------------

function applySettings(settings, isPro) {
  $('toggle-auto').checked       = settings.autoSuspend      ?? true;
  $('input-delay').value         = settings.autoSuspendDelay ?? 30;
  $('toggle-pinned').checked     = settings.suspendPinned    ?? false;
  $('toggle-audible').checked    = settings.suspendAudible   ?? false;
  $('toggle-capturing').checked  = settings.suspendCapturing ?? false;
  $('toggle-sync').checked       = settings.syncSettings     ?? false;

  $('row-delay').hidden = !$('toggle-auto').checked;

  // Lock Pro features for free users
  const syncCard = $('card-sync');
  if (syncCard) syncCard.classList.toggle('pro-locked', !isPro);
}

function bindGeneralEvents() {
  $('toggle-auto').addEventListener('change', () => {
    $('row-delay').hidden = !$('toggle-auto').checked;
  });

  $('btn-save-general').addEventListener('click', async () => {
    const currentRes = await msg('GET_SETTINGS');
    const current = currentRes.ok ? currentRes.settings : {};
    const settings = {
      ...current,
      autoSuspend:      $('toggle-auto').checked,
      autoSuspendDelay: Math.max(1, parseInt($('input-delay').value, 10) || 30),
      suspendPinned:    $('toggle-pinned').checked,
      suspendAudible:   $('toggle-audible').checked,
      suspendCapturing: $('toggle-capturing').checked,
      syncSettings:     $('toggle-sync').checked,
      whitelist:        await getCurrentWhitelist(),
    };

    const res = await msg('SAVE_SETTINGS', { settings });
    if (res.ok) showSaveConfirm('save-confirm-general');
  });
}

// ---------------------------------------------------------------------------
// Shortcuts
// ---------------------------------------------------------------------------

const SHORTCUT_LABELS = {
  '_execute_action':   'Open Slumber popup',
  'suspend-tab':       'Sleep the current tab',
  'unsuspend-tab':     'Wake the current tab',
  'unsuspend-all-tabs':'Wake all sleeping tabs in the current window',
};

async function loadShortcuts() {
  const commands = await chrome.commands.getAll();
  const card     = $('shortcuts-card');
  if (!card) return;

  card.innerHTML = '';

  commands.forEach(cmd => {
    const label   = SHORTCUT_LABELS[cmd.name] ?? cmd.description ?? cmd.name;
    const binding = cmd.shortcut || null;

    const row = document.createElement('div');
    row.className = 'setting-row shortcut-row';

    const info = document.createElement('span');
    info.className   = 'setting-label';
    info.textContent = label;

    const badge = document.createElement('div');
    badge.className = 'shortcut-badge';

    if (binding) {
      binding.split('+').forEach((part, i) => {
        if (i > 0) {
          const sep = document.createElement('span');
          sep.className   = 'shortcut-sep';
          sep.textContent = '+';
          badge.appendChild(sep);
        }
        const key = document.createElement('kbd');
        key.textContent = part.trim();
        badge.appendChild(key);
      });
    } else {
      const unset = document.createElement('span');
      unset.className   = 'shortcut-unset';
      unset.textContent = 'Not set';
      badge.appendChild(unset);
    }

    row.append(info, badge);
    card.appendChild(row);
  });
}

function bindShortcutsEvents() {
  $('btn-edit-shortcuts').addEventListener('click', () => {
    chrome.tabs.create({ url: 'chrome://extensions/shortcuts' });
  });
}

// ---------------------------------------------------------------------------
// Schedule
// ---------------------------------------------------------------------------

async function loadSchedule() {
  const [res, { slumber_license }] = await Promise.all([
    msg('GET_SETTINGS'),
    chrome.storage.sync.get('slumber_license'),
  ]);
  const schedule = res.ok ? (res.settings.schedule ?? defaultSchedule()) : defaultSchedule();
  applyScheduleUI(schedule);

  const isPro = Boolean(slumber_license?.valid);
  const card    = $('schedule-card');
  const saveBtn = $('btn-save-schedule');
  if (card)    card.classList.toggle('pro-locked', !isPro);
  if (saveBtn) saveBtn.disabled = !isPro;
}

function defaultSchedule() {
  return { enabled: false, days: [1, 2, 3, 4, 5], startTime: '09:00', endTime: '18:00' };
}

function applyScheduleUI(schedule) {
  $('toggle-schedule').checked  = schedule.enabled ?? false;
  $('schedule-config').hidden   = !schedule.enabled;

  const days = Array.isArray(schedule.days) ? schedule.days : [1, 2, 3, 4, 5];
  document.querySelectorAll('.day-btn').forEach(btn => {
    btn.classList.toggle('active', days.includes(parseInt(btn.dataset.day, 10)));
  });

  $('input-start-time').value = schedule.startTime ?? '09:00';
  $('input-end-time').value   = schedule.endTime   ?? '18:00';
}

function bindScheduleEvents() {
  $('toggle-schedule').addEventListener('change', () => {
    $('schedule-config').hidden = !$('toggle-schedule').checked;
  });

  document.querySelectorAll('.day-btn').forEach(btn => {
    btn.addEventListener('click', () => btn.classList.toggle('active'));
  });

  $('btn-save-schedule').addEventListener('click', saveSchedule);
}

async function saveSchedule() {
  const enabled   = $('toggle-schedule').checked;
  const days      = [...document.querySelectorAll('.day-btn.active')]
    .map(btn => parseInt(btn.dataset.day, 10));
  const startTime = $('input-start-time').value || '09:00';
  const endTime   = $('input-end-time').value   || '18:00';

  const currentRes = await msg('GET_SETTINGS');
  const current = currentRes.ok ? currentRes.settings : {};
  const settings = { ...current, schedule: { enabled, days, startTime, endTime } };

  const res = await msg('SAVE_SETTINGS', { settings });
  if (res.ok) showSaveConfirm('save-confirm-schedule');
}

// ---------------------------------------------------------------------------
// Whitelist
// ---------------------------------------------------------------------------

let _whitelist = [];

async function loadWhitelist() {
  const [res, { slumber_license }] = await Promise.all([
    msg('GET_SETTINGS'),
    chrome.storage.sync.get('slumber_license'),
  ]);
  _whitelist = res.ok ? (res.settings.whitelist ?? []) : [];
  renderDomainList();

  const isPro = Boolean(slumber_license?.valid);

  // Lock if not Pro
  const card = $('whitelist-card');
  if (card) card.classList.toggle('pro-locked', !isPro);

  // Disable "Clear all" for free users
  const clearBtn = $('btn-clear-whitelist');
  if (clearBtn) {
    clearBtn.disabled = !isPro;
    clearBtn.title = isPro ? '' : 'Upgrade to Pro to manage whitelist';
  }
}

function renderDomainList() {
  const list  = $('domain-list');
  const empty = $('empty-domains');

  list.innerHTML = '';

  if (_whitelist.length === 0) {
    empty.hidden = false;
    return;
  }
  empty.hidden = true;

  _whitelist.forEach(domain => {
    const row = document.createElement('div');
    row.className = 'domain-row';
    row.setAttribute('role', 'listitem');

    const name = document.createElement('span');
    name.className   = 'domain-name';
    name.textContent = domain;

    const removeBtn = document.createElement('button');
    removeBtn.className   = 'btn-danger-sm';
    removeBtn.textContent = 'Remove';
    removeBtn.addEventListener('click', () => removeDomain(domain));

    row.append(name, removeBtn);
    list.appendChild(row);
  });
}

async function addDomain() {
  const input  = $('whitelist-input');
  const raw    = input.value.trim().toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/\/.*$/, '');

  if (!raw || _whitelist.includes(raw)) {
    input.value = '';
    return;
  }

  _whitelist.push(raw);
  input.value = '';
  renderDomainList();
  await persistWhitelist();
  showSaveConfirm('save-confirm-whitelist');
}

async function removeDomain(domain) {
  _whitelist = _whitelist.filter(d => d !== domain);
  renderDomainList();
  await persistWhitelist();
  showSaveConfirm('save-confirm-whitelist');
}

async function persistWhitelist() {
  const settingsRes = await msg('GET_SETTINGS');
  if (!settingsRes.ok) return;
  await msg('SAVE_SETTINGS', {
    settings: { ...settingsRes.settings, whitelist: _whitelist },
  });
}

async function getCurrentWhitelist() {
  return _whitelist;
}

function bindWhitelistEvents() {
  $('btn-add-domain').addEventListener('click', addDomain);
  $('whitelist-input').addEventListener('keydown', e => {
    if (e.key === 'Enter') addDomain();
  });
  $('btn-clear-whitelist').addEventListener('click', async () => {
    const proRes = await msg('GET_SETTINGS');
    if (!proRes.isPro) return;
    if (!confirm('Clear all whitelisted domains?')) return;
    _whitelist = [];
    renderDomainList();
    await persistWhitelist();
  });
}

// ---------------------------------------------------------------------------
// License — Paddle + Cloudflare Worker validation
// ---------------------------------------------------------------------------

async function loadLicense() {
  const { slumber_license } = await chrome.storage.sync.get('slumber_license');
  renderLicenseState(slumber_license ?? null);
}

function renderLicenseState(license) {
  const active = Boolean(license?.valid);
  $('pro-active-card').hidden = !active;
  $('free-card').hidden       =  active;
  if (active) {
    $('pro-txn-id').textContent    = license.licenseKey ?? '—';
    $('pro-license-email').textContent = license.email ? `Registered to ${license.email}` : '';
  }
}

async function validateLicenseKey(key) {
  const res = await fetch(
    `${VALIDATE_ENDPOINT}?key=${encodeURIComponent(key)}`,
    { signal: AbortSignal.timeout(10_000) },
  );
  if (!res.ok) throw Object.assign(new Error(`HTTP ${res.status}`), { status: res.status });
  return res.json(); // { valid: bool, email: string }
}

async function activateLicense(key) {
  const btn    = $('btn-activate-key');
  const input  = $('license-key-input');

  btn.disabled   = true;
  btn.textContent = 'Checking…';
  input.disabled  = true;
  setLicenseStatus('');

  let data;
  try {
    data = await validateLicenseKey(key);
  } catch (err) {
    btn.disabled    = false;
    btn.textContent = 'Activate';
    input.disabled  = false;

    // Network failure — keep whatever state is already stored
    const { slumber_license } = await chrome.storage.sync.get('slumber_license');
    if (slumber_license?.valid) {
      setLicenseStatus('Could not reach the server. Your existing activation has been kept.', 'warn');
    } else {
      setLicenseStatus('Could not reach the validation server. Check your connection and try again.', 'error');
    }
    return;
  }

  btn.disabled    = false;
  btn.textContent = 'Activate';
  input.disabled  = false;

  if (!data.valid) {
    setLicenseStatus('This key was not recognised. Check your Paddle receipt and try again.', 'error');
    await chrome.storage.sync.remove('slumber_license');
    renderLicenseState(null);
    return;
  }

  const license = {
    licenseKey:  key,
    valid:       true,
    email:       data.email ?? '',
    validatedAt: Date.now(),
  };
  await chrome.storage.sync.set({ slumber_license: license });
  renderLicenseState(license);
  setLicenseStatus('License activated — Slumber Pro is now active.', 'success');
}

async function deactivateLicense() {
  if (!confirm('Remove the Pro license from this Chrome profile? You can re-enter your key later.')) return;
  await chrome.storage.sync.remove('slumber_license');
  renderLicenseState(null);
}

function setLicenseStatus(message, type = '') {
  const el = $('license-key-status');
  if (!el) return;
  el.textContent = message;
  el.className   = 'license-key-status' + (type ? ` is-${type}` : '');
  el.hidden      = !message;
}

function bindLicenseEvents() {
  $('btn-upgrade').addEventListener('click', () => {
    chrome.tabs.create({ url: PADDLE_PAYMENT_LINK });
  });

  $('link-login').addEventListener('click', e => {
    e.preventDefault();
    $('license-key-wrap').hidden = false;
    $('license-key-input').focus();
  });

  $('btn-activate-key').addEventListener('click', async () => {
    const raw = $('license-key-input').value.trim();
    if (!LICENSE_KEY_RE.test(raw)) {
      setLicenseStatus('Invalid format — key should look like XXXX-XXXX-XXXX-XXXX.', 'error');
      return;
    }
    await activateLicense(raw);
  });

  $('license-key-input').addEventListener('keydown', e => {
    if (e.key === 'Enter') $('btn-activate-key').click();
  });

  $('license-key-input').addEventListener('input', () => setLicenseStatus(''));

  $('link-deactivate').addEventListener('click', e => {
    e.preventDefault();
    deactivateLicense();
  });
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

const STATS_KEY  = 'slumber_stats';
const MB_PER_TAB = 80; // conservative estimate, MB saved per suspended tab

async function loadStats() {
  const { slumber_stats: stats = {}, suspended = {} } =
    await chrome.storage.local.get([STATS_KEY, 'suspended']);

  const totalSuspended  = stats.totalSuspended  ?? 0;
  const installDate     = stats.installDate     ?? Date.now();
  const currentSleeping = Object.keys(suspended).length;
  const daysActive      = Math.max(1, Math.floor((Date.now() - installDate) / 86_400_000));
  const memoryMB        = totalSuspended * MB_PER_TAB;

  $('stat-total-suspended').textContent   = totalSuspended.toLocaleString();
  $('stat-currently-sleeping').textContent = currentSleeping.toLocaleString();
  $('stat-memory').textContent            = memoryMB >= 1000
    ? `~${(memoryMB / 1000).toFixed(1)} GB`
    : `~${memoryMB} MB`;
  $('stat-days-active').textContent       = daysActive.toLocaleString();
}

function bindStatsEvents() {
  $('btn-reset-stats').addEventListener('click', async () => {
    if (!confirm('Reset all stats? This cannot be undone.')) return;
    await chrome.storage.local.set({
      [STATS_KEY]: { totalSuspended: 0, installDate: Date.now() },
    });
    loadStats();
  });
}

// ---------------------------------------------------------------------------
// Welcome card (first install only)
// ---------------------------------------------------------------------------

async function maybeShowWelcomeCard() {
  const { slumber_welcomed } = await chrome.storage.local.get('slumber_welcomed');
  if (slumber_welcomed) return;

  const card    = $('welcome-card');
  const dismiss = $('welcome-card-dismiss');
  if (!card) return;

  card.hidden = false;

  dismiss.addEventListener('click', async () => {
    card.style.animation  = 'none';
    card.style.opacity    = '0';
    card.style.transition = 'opacity 0.2s';
    setTimeout(() => { card.hidden = true; }, 200);
    await chrome.storage.local.set({ slumber_welcomed: true });
  });
}

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------

init();
